services:
  - type: web
    name: n8n-selfhosted
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: WEBHOOK_URL
        value: https://n8n-selfhosted-vsg2.onrender.com
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: yourusername
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourpassword
